### ISSUE TITLE
Some clarification

### ISSUE THREAD

**Issue by hisnawi** [IvanMalison/dotfiles#20]
I am liking your emacs configuration and I am adapting parts of it in mine.
I have a question regarding helm and ido.
Helm works fine for me but I can't see the effect of ido anywhere. Even if I removed the code I don't see the difference in navigation. Is that part of the setup needed? And what kind of effect does it add?

Thanks.

**Comment by IvanMalison** [comment]
ido is only used for file selection (C-x C-f and some other places)

**Comment by hisnawi** [comment]
Thanks
